[package]
name = "day02-1202-program-alarm"
version = "0.1.0"
authors = ["Paul Souche <paul.souche@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
